# Generated by Django 4.1.6 on 2023-03-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goalcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcomment',
            name='text',
            field=models.CharField(max_length=511, verbose_name='Текст'),
        ),
    ]
