# Generated by Django 4.1.6 on 2023-03-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
