# Generated by Django 4.1.6 on 2023-03-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tguser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
